environment:
  nodejs_version: "0.10"
  API_URL: https://#{api.hostheader}/api/v2
  FACEBOOK_APPID: #{facebook.appid}
  GITHUB_APPID: #{github.appid}
  GOOGLE_APPID: #{google.appid}
  HTML5_MODE: #{html5mode}
  INTERCOM_APPID: #{intercom.appid}
  LIVE_APPID: #{live.appid}
  STRIPE_PUBLISHABLE_KEY: #{stripe.publishablekey}
  SYSTEM_NOTIFICATION_MESSAGE: #{systemnotificationmessage}

install:
  - ps: Install-Product node $env:nodejs_version
  - cd src
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install
  - bower install

build_script:
  - grunt build

test_script:
  - grunt test
  
after_test:
  - cd ..
  - nuget pack

artifacts:
  - path: *.nupkg

notifications:
  - provider: HipChat
    auth_token:
      secure: WxN+iiJf8AT50n50y8/AkTMl+Cvma6lwSdffFaBU6/o=
    room: Notifications
    
    
