version: 2.1.{build}

environment:
  BUILD_REPO_URL:
    secure: vuYBT6D5arel88+Py/H3nnMPd4hInIXvr2cwhJaZSSSvJnmg+9sX1P5+bTWaJskYpGztHVMg0Iq7hgUCMKjh23w8WBrutLiUsixRE0LBjroIVJaRsYG1okSko0fNKVOCyOLKGt19Qrk45/TrTFlGMQ==

install:
  - cd src
  - npm install
  - node_modules\.bin\bower install

build_script:
  - node_modules\.bin\grunt build

test_script:
  - node_modules\.bin\grunt test

after_deploy:
  - node_modules\.bin\grunt deploy
  
notifications:
  - provider: Slack
    auth_token:
      secure: PigIGGo7UUDwdb0KGM/s7OfpAng/OMJx7q33jKfzudFBiXi1EBEd0DRmkbCc7CiX
    channel: notifications
