version: 2.8.{build}

environment:
    BUILD_REPO_URL:
        secure: vuYBT6D5arel88+Py/H3nnMPd4hInIXvr2cwhJaZSSSvJnmg+9sX1P5+bTWaJskYpGztHVMg0Iq7hgUCMKjh23w8WBrutLiUsixRE0LBjroIVJaRsYG1okSko0fNKVOCyOLKGt19Qrk45/TrTFlGMQ==

install:
- ps: Install-Product node 8
- npm install
- npm install -g angular-cli-ghpages
- npm install -g @angular/cli

build_script:
- node_modules\.bin\ng build

after_test:
- tar -zcvf dist\exceptionless.zip dist\exceptionless
- ps: Get-ChildItem .\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName ReleaseArtifacts }
- IF "%APPVEYOR_PULL_REQUEST_NUMBER%"=="" IF "%APPVEYOR_REPO_BRANCH%"=="" ngh --dir=dist\exceptionless --no-silent --name="AppVeyor CI" --email=builds@exceptionless.io --branch=feature/angular6 --repo=%BUILD_REPO_URL%
- IF "%APPVEYOR_PULL_REQUEST_NUMBER%"=="" IF not "%APPVEYOR_REPO_BRANCH%"=="" ngh --dir=dist\exceptionless --no-silent --name="AppVeyor CI" --email=builds@exceptionless.io --branch=%APPVEYOR_REPO_BRANCH%  --repo=%BUILD_REPO_URL%

artifacts:
- path: .\*.zip
  name: ReleaseArtifacts

deploy:
    provider: GitHub
    auth_token:
        secure: 0s81q7bweVLTFSOKxnIhan7el6bIFiN8HJ1kYJzOkeFXX7wgGSq9bs/rV53X9qpf
    artifact: ReleaseArtifacts
    draft: true
    on:
        branch: master
        appveyor_repo_tag: true

notifications:
- provider: Slack
  channel: '#notifications'
  auth_token:
      secure: GniMpFE62HprSyQNQoej/VSBnxn2GNnTrca3BnF8+ikMdqduO4Ts4t297teZF6wDAmGwnOtXusctUla8+WxLFkIztvVCS2Z1RG/DvEDYoc0=
