version: 2.0.{build}

install:
  - cd src
  - npm install
  - node_modules\.bin\bower install

build_script:
  - node_modules\.bin\grunt build

test_script:
  - node_modules\.bin\grunt test

after_deploy:
  - node_modules\.bin\grunt deploy
  
notifications:
  - provider: Slack
    auth_token:
      secure: PigIGGo7UUDwdb0KGM/s7OfpAng/OMJx7q33jKfzudFBiXi1EBEd0DRmkbCc7CiX
    channel: notifications