version: 2.8.{build}
image: ubuntu
clone_depth: 2

services:
  - docker

pull_requests:
  do_not_increment_build_number: true

init:
  - git config --global core.autocrlf input

environment:
  UI_DOCKER_IMAGE: ui-ci

build_script:
  - docker build --target testrunner -t exceptionless:test .
  - docker run -e APPVEYOR_API_URL --net=host -v $(pwd)/TestResults:/app/artifacts exceptionless:test

after_build:
  - docker build --target ui -t $UI_DOCKER_IMAGE .
  - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
  - >-
    for tag in {$APPVEYOR_BUILD_NUMBER,latest}; do
      (
        docker tag $UI_DOCKER_IMAGE exceptionless/$UI_DOCKER_IMAGE:$tag
        docker push exceptionless/$UI_DOCKER_IMAGE:$tag
      ) &
    done
    wait

artifacts:
  - path: artifacts/*.xml
    name: Test Results

notifications:
  - provider: Slack
    channel: '#notifications'
    auth_token:
      secure: GniMpFE62HprSyQNQoej/VSBnxn2GNnTrca3BnF8+ikMdqduO4Ts4t297teZF6wDAmGwnOtXusctUla8+WxLFkIztvVCS2Z1RG/DvEDYoc0=
