version: 2.0.{build}

environment:
  nodejs_version: "0.10"
  API_URL: https://#{api.hostheader}/api/v2
  FACEBOOK_APPID: "#{facebook.appid}"
  GITHUB_APPID: "#{github.appid}"
  GOOGLE_APPID: "#{google.appid}"
  HTML5_MODE: "#{html5mode}"
  INTERCOM_APPID: "#{intercom.appid}"
  LIVE_APPID: "#{live.appid}"
  STRIPE_PUBLISHABLE_KEY: "#{stripe.publishablekey}"
  SYSTEM_NOTIFICATION_MESSAGE: "#{systemnotificationmessage}"
  OCTOPUS_API_URL: https://deploy.codesmithtools.com/api
  OCTOPUS_API_KEY:
    secure: 9Uk1fnTNb36QtrWfRCe9vrqVsBaEXGcM1K1mRoLUB0A=

install:
  - ps: Install-Product node $env:nodejs_version
  - cd src
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install
  - bower install

build_script:
  - grunt build

test_script:
  - grunt test
  
after_test:
  - cd ..
  - ps: nuget pack -Version $env:APPVEYOR_BUILD_VERSION
  - nuget install OctopusTools
  - ps: '&(ls .\OctopusTools*\Octo.exe) create-release --project="Exceptionless UI" --version "$env:APPVEYOR_BUILD_VERSION" --server "$env:OCTOPUS_API_URL" --apiKey "$env:OCTOPUS_API_KEY" --deployto Dev'

artifacts:
  - path: '*.nupkg'

deploy:
  - provider: Environment
    name: MyGet

notifications:
  - provider: HipChat
    auth_token:
      secure: WxN+iiJf8AT50n50y8/AkTMl+Cvma6lwSdffFaBU6/o=
    room: Notifications
